// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import { group } from "k6";

export const options = {
  stages: [
    { duration: '30s', target: 20 },
    { duration: '1m30s', target: 10 },
    { duration: '20s', target: 0 },
  ],
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    USERNAME: "test@example.com",
    PASSWORD: "superCroc2020",
    FIRSTNAME: "John",
    LASTNAME: "Doe",
    EMAIL: "test@example.com",
    ACCESS: null,
    REFRESH: null,
    CROCID: null
  }
});

export default function() {
  group("Product", function() {
    postman[Request]({
      name: "product",
      id: "b1050292-b9be-40cd-9eaa-72fdedabc73f",
      method: "GET",
      address: "http://localhost:5430/api/product",
      post(response) {
        pm.test("Status code is 200", function() {
          pm.response.to.have.status(200);
        });
      }
    });

    postman[Request]({
      name: "product-id",
      id: "d8fb3bd1-cb65-41a6-b59a-072d6ae0def5",
      method: "GET",
      address:
        "http://localhost:5430/api/product/36872480-f793-47c2-a536-08daaf09bddc"
    });

    postman[Request]({
      name: "product-list",
      id: "78b26952-0ce9-4f70-b454-093ce7a9feea",
      method: "GET",
      address:
        "http://localhost:5430/api/product/list/36872480-f793-47c2-a536-08daaf09bddc"
    });
  });
}
